### PR TITLE
Add image related operations

### PR DESCRIPTION
**Pull request by HanbumKo**
I wanted to make classifying model but this library only has MNIST data.
So I made some image related operations and will make soon.
Also I made Tensor constructor -> Tensor(int[][] intD) which change int type to double type and call Tensor(double[][] d)

1. Add int[][] Tensor type(change int to double)
2. Add ImageUtils that deals with Image related operations
3. Add Test code for ImageUtils

Reference : http://entropymine.com/imageworsener/grayscale/

### CODE REVIEW

**Comment by Daniel-Liu-c0deb0t** [comment]
What is the license on the images you included? Also can you separate image reading and grayscale conversion into different methods? Do we need another constructor for a Tensor? Why can't we use the existing 2D constructor?

Also maybe finish the ImageUtils function before merging?

Thanks for your contribution!

**Comment by HanbumKo** [comment]
1. What is the license on the images you included?
- What I uploaded is 'Set14 dataset', it is mostly used in Super-Resolution problem. Many experiments use these dataset(BSD100, Set5, Set14, etc...). Also many people uploaded these dataset on their repositories. So I think it is ok.

2. Also can you separate image reading and grayscale conversion into different methods?
- Ok. I will do that.

3. Do we need another constructor for a Tensor?
- Now, all Tensor shape has actually 1 column vector. Maybe we will need to 2D Tensor or 3D Tensor. But now, we don't need to fix this structure. When we need that, have to fix it.

4. Why can't we use the existing 2D constructor?
- I don't understand exact meaning of this question, It only has double type constructor. So I made int data type constructor.(Is it answer to the question??)

5. Also maybe finish all ImageUtil methods before merging?
- Ok. I will request when I'm done it.

**Comment by Daniel-Liu-c0deb0t** [comment]
This pull request is useless now that the newer one is merged right?

**Comment by HanbumKo** [comment]
Right. New one is kind of upgrade version of this request.

**Pull request closed without merging**
